### ISSUE TITLE
After updating IP to v1.6.0 and PHP to 8.1 invoices/generate_pdf no longer works (with SVG?)

### ISSUE THREAD

**Issue by ctsde-markus** [InvoicePlane/InvoicePlane#898]
## Expected Behavior

Generate a PDF of an invoice.

## Current Behavior

I get errors stating that it could not find an image file:

```text
An uncaught Exception was encountered

Type: Mpdf\MpdfImageException

Message: Could not find image file (file:///usr/local/www/invoiceplane/app-v1.6.0/uploads/CTS_Logo_Vector.svg)

Filename: /usr/local/www/invoiceplane/app-v1.6.0/vendor/mpdf/mpdf/src/Image/ImageProcessor.php

Line Number: 589

Backtrace:

File: /usr/local/www/invoiceplane/app-v1.6.0/vendor/mpdf/mpdf/src/Image/ImageProcessor.php
Line: 211
Function: imageError

File: /usr/local/www/invoiceplane/app-v1.6.0/vendor/mpdf/mpdf/src/Tag/Img.php
Line: 276
Function: getImage

File: /usr/local/www/invoiceplane/app-v1.6.0/vendor/mpdf/mpdf/src/Tag.php
Line: 240
Function: open

File: /usr/local/www/invoiceplane/app-v1.6.0/vendor/mpdf/mpdf/src/Mpdf.php
Line: 13875
Function: OpenTag

File: /usr/local/www/invoiceplane/app-v1.6.0/application/helpers/mpdf_helper.php
Line: 96
Function: WriteHTML

File: /usr/local/www/invoiceplane/app-v1.6.0/application/helpers/pdf_helper.php
Line: 105
Function: pdf_create

File: /usr/local/www/invoiceplane/app-v1.6.0/application/modules/invoices/controllers/Invoices.php
Line: 272
Function: generate_invoice_pdf

File: /usr/local/www/invoiceplane/app-v1.6.0/index.php
Line: 329
Function: require_once
```

The file itself is there and the user running the php-fpm process can read it, in fact it even owns the file:

```text
invplane> ls -l /usr/local/www/invoiceplane/app-v1.6.0/uploads/CTS_Logo_Vector.svg
-rw-r--r--  1 invplane  invplane  337897 Jul 22  2020 /usr/local/www/invoiceplane/app-v1.6.0/uploads/CTS_Logo_Vector.svg
```

I can still download already created .pdf Files from `.../uploads/archive/` so there can't be any permission problem down the path.

I checked with phpinfo() that all required modules for mpdf are enabled:

- [x] mbstring
- [x] gd
- [x] zlib
- [x] bcmath
- [x] xml

## Steps to Reproduce

Update my installation vom 1.5.11 to 1.6.0 and upgrade from PHP-7.4 to PHP-8.1.13 on FreeBSD. The previous version worked fine with PHP-7.4.

## Failure Logs

I only see a 500 error in the nginx-vhost-access.log. No further error messages than those mentioned above. It seems that it no longer can interpret the .SVG file in mpdf with PHP-8.1.

**Comment by nielsdrost7** [comment]
We just had a pull-request resolving this issue:
https://github.com/InvoicePlane/InvoicePlane/pull/897/files
It's already merged into the development branch.

Would you mind quickly change that file, so it resolves your issue

**Comment by ctsde-markus** [comment]
> @ctsde-markus thank you for the bug report.
> 
> We just had a pull-request resolving this issue: https://github.com/InvoicePlane/InvoicePlane/pull/897/files It's already merged into the development branch.
> 
> Would you mind quickly changing that file, so it resolves your issue

This solves the problem for me! Thank you very much!

Bye
Markus

**Comment by naui95** [comment]
Closing issue. Fixed by MR #897

**Comment by reproteq** [comment]
i have same issue  and solved with this 

if ($CI->mdl_settings->setting('invoice_logo')) {
.................

$absolutePath = dirname(dirname(__DIR__));
return '<img src="' . $absolutePath . '/uploads/' . $CI->mdl_settings->setting('invoice_logo') . '">';

**Comment by nielsdrost7** [comment]
@reproteq does that mean that the solution in https://github.com/InvoicePlane/InvoicePlane/pull/897/files didn't work for you and you had to make extra adjustments with that absolute path?

**Comment by reproteq** [comment]
exactly that

**Comment by nielsdrost7** [comment]
Reopened: In some cases the logo still doesn't show. [Above solution](https://github.com/InvoicePlane/InvoicePlane/issues/898#issuecomment-1605951464) helps solve that.

Requires a PR for the `development` branch, so we can add it to the new upcoming beta version

**Comment by nielsdrost7** [comment]
Let's see if this code is in Beta, otherwise change it.
Also see comments on the closed pull-request regarding the PDF Logo


On line 22 to 25:
```
if ($CI->mdl_settings->setting('invoice_logo')) {
        $absolutePath = dirname(dirname(__DIR__));
		return '<img src="' . $absolutePath . '/uploads/' . $CI->mdl_settings->setting('invoice_logo') . '">';
    }
```

On line 39 to 42:

```
if ($CI->mdl_settings->setting('invoice_logo')) {
		$absolutePath = dirname(dirname(__DIR__));
		return '<img src="' . $absolutePath . '/uploads/' . $CI->mdl_settings->setting('invoice_logo') . '" id="invoice-logo">';
    }
```

**Comment by nielsdrost7** [comment]
@reproteq I fixed the bug, checkout the PR: https://github.com/InvoicePlane/InvoicePlane/pull/964/files
Solution will be merged in new version, coming up soon
